seed: 42
data:
  container: "precomputed://gs://dkronauer-ant-001-alignment-final/aligned"
  cache: "/lustre/fs4/kron_lab/scratch/jlee11/nt_predictions/caches" 
  voxel_size: [8, 8, 42]
  channels: 1
  use_https: true
  progress: false
  parallel: true

seed: 12345 

gt:
  neurotransmitters: 
    - acetylcholine
    - dopamine
    - gaba
    - glutamate
    - octopamine
    - peptide
  base: /lustre/fs4/kron_lab/scratch/jlee11/nt_predictions/imported_synapses_20250723.feather
  train: /lustre/fs4/kron_lab/scratch/jlee11/nt_predictions/train_data.feather
  val: /lustre/fs4/kron_lab/scratch/jlee11/nt_predictions/val_data.feather
  body_id: "neuron_id" 
  nt_name: "neurotransmitter"
  val_size: 0.1

train:
  experiment_dir: "/lustre/fs4/kron_lab/scratch/jlee11/nt_predictions/train_results"
  input_shape: 
    - 80
    - 80
    - 16
  batch_size: 16
  learning_rate: 0.0001
  epochs: 100

validate: 
  batch_size: 32