data:
  container: "precomputed://gs://dkronauer-ant-001-alignment-final/aligned"
  dataset: "s0"
  voxel_size: [8, 8, 42]
  channels: 1

gt:
  neurotransmitter: 
    - acetylcholine
    - dopamine
    - gaba
    - glutamate
    - octopamine
    - peptide
    - tyramine
  base: /lustre/fs4/kron_lab/scratch/llopes/neurotransmitters/gt.feather
  train: /lustre/fs4/kron_lab/scratch/llopes/neurotransmitters/train_data.feather
  val: /lustre/fs4/kron_lab/scratch/llopes/neurotransmitters/val_data.feather
  body_id: "neuron_id" 
  nt_name: "neurotransmitter"

train:
  experiment_dir: "/lustre/fs4/kron_lab/scratch/llopes/neurotransmitters/"
  input_shape: # TODO specify the input shape of the model
    - 80
    - 80
    - 16
  log_every: 100
  num_iterations: 100000
  batch_size: 16
  save_every: 10000
  snapshot_every: 10000
  learning_rate: 0.0001
  num_cache_workers: 12

validate: 
  batch_size: 32
  num_partitions: 10
  partition_id: 1
  output_dir: "/lustre/fs4/kron_lab/scratch/llopes/neurotransmitters/validation" 