seed: 42
data:
  container: "precomputed://gs://dkronauer-ant-001-alignment-final/aligned"
  cache: "/ru-auth/local/home/jlee11/scratch/nt_predictions/20250819_caches" 
  voxel_size: [8, 8, 42]
  channels: 1
  use_https: true
  progress: false
  parallel: true

seed: 42 

gt:
  neurotransmitters: 
    - acetylcholine
    - dopamine
    - gaba
    - glutamate
    - octopamine
    - peptide
  base: /ru-auth/local/home/jlee11/scratch/nt_predictions/imported_synapses_20250819.feather
  train: /ru-auth/local/home/jlee11/scratch/nt_predictions/train_data_20250819.feather
  val: /ru-auth/local/home/jlee11/scratch/nt_predictions/val_data_20250819.feather
  body_id: "neuron_id" 
  nt_name: "neurotransmitter"
  val_size: 0.1

train:
  base: "/ru-auth/local/home/jlee11/scratch/nt_predictions/train_results_20250819"
  experiment_dir: "/ru-auth/local/home/jlee11/scratch/nt_predictions/train_results_20250819"
  input_shape: 
    - 80
    - 80
    - 16
  batch_size: 16 # increase for faster performance
  learning_rate: 0.0001
  epochs: 100

validate: 
  batch_size: 32