[project]
authors = ["Diane Adjavon <diane.adjavon@icloud.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "CRANTb-transmitters"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.13"

[pypi-dependencies]
pandas = ">=2.3.1, <3"
typing = "*"
scikit-learn = "*"
omegaconf = "*"
numpy = "*"
monai = "*"
tqdm = "*"
